[development]
address = "localhost"
port = 8000
log = "debug"
limits = { json = 8388608 } # 8 MiB

[staging]
address = "0.0.0.0"
port = 80
log = "debug"
limits = { json = 8388608 } # 8 MiB

[production]
address = "0.0.0.0"
port = 80
log = "critical"
limits = { json = 8388608 } # 8 MiB
