[development]
address = "localhost"
port = 8000
log = "debug"
limits = { json = 16777216 } # 16 MiB

[staging]
address = "0.0.0.0"
port = 80
log = "debug"
limits = { json = 16777216 } # 16 MiB

[production]
address = "0.0.0.0"
port = 80
log = "critical"
limits = { json = 16777216 } # 16 MiB
